[pytest]
pythonpath = .
markers =
    products: тесты productsList
    brands: тесты brandsList
    search: тесты searchProduct
    login: тесты verifyLogin
    registration: тесты createAccount
    delete: тесты deleteAccount
    update: тесты updateAccount
    get_user: тесты getUserDetailByEmail

filterwarnings =
    ignore::urllib3.exceptions.NotOpenSSLWarning
